/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import java.net.MalformedURLException;

public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {

        // This is to remove unnecessary warnings from your console
        System.setProperty("java.util.logging.config.file", "logging.properties");

        // TestCases tests = new TestCases(); // Initialize your test class
        // tests.testCase01();

        // TODO: call your test case functions one after other here

        // SearchAmazon searchAmazon = new SearchAmazon();
        // searchAmazon.testCase01();

        // BookMyShowCountHyperlinks countHyperlinks = new BookMyShowCountHyperlinks();
        // countHyperlinks.testCase01();

        // ImageURLs imageURLs = new ImageURLs();
        // imageURLs.testCase01();

        Linkedin linkedin = new Linkedin();
        linkedin.testCase01();

        // END Tests
        // tests.endTest(); // End your test by clearning connections and closing
        // browser
        // searchAmazon.endTest();
        // countHyperlinks.endTest();
        // imageURLs.endTest();
        linkedin.endTest();
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}
